//! Launches the user's shell with command hooks installed.

use std::fs;
use std::os::unix::fs::DirBuilderExt;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus};

use anyhow::{Context, Result, bail};
use nix::sys::signal::{SigHandler, Signal, signal};

use crate::session::ENV_SESSION_DIR;

/// Absolute path of the exarare binary, so hooks work even if PATH changes (e.g. `sudo -i`).
pub const ENV_BIN: &str = "EXARARE_BIN";
const ENV_ORIG_ZDOTDIR: &str = "EXARARE_ORIG_ZDOTDIR";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    Bash,
    Zsh,
}

impl Kind {
    pub fn detect(shell: &Path) -> Result<Self> {
        let name = shell.file_name().and_then(|n| n.to_str()).unwrap_or("");
        match name {
            n if n.starts_with("bash") => Ok(Kind::Bash),
            n if n.starts_with("zsh") => Ok(Kind::Zsh),
            _ => bail!(
                "unsupported shell {}: exarare supports bash and zsh",
                shell.display()
            ),
        }
    }
}

/// `--shell`, then `$SHELL`, then bash.
pub fn resolve(shell: Option<PathBuf>) -> PathBuf {
    shell
        .or_else(|| std::env::var_os("SHELL").map(PathBuf::from))
        .unwrap_or_else(|| PathBuf::from("/bin/bash"))
}

const BASH_RC: &str = r#"# Generated by exarare. Do not edit.
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi

# Commands hidden from history would also be hidden from the record.
HISTCONTROL=
HISTIGNORE=
set -o history

# 2: before the first prompt, 1: waiting for a command, 0: a command is running.
__exarare_state=2

__exarare_preexec() {
  [ -n "${COMP_LINE-}" ] && return
  [ "$__exarare_state" = 1 ] || return
  __exarare_state=0
  local line
  line=$(HISTTIMEFORMAT= builtin history 1)
  [[ $line =~ ^\ *[0-9]+\*?\ +(.*)$ ]] && line=${BASH_REMATCH[1]}
  "$EXARARE_BIN" __hook pre --cwd "$PWD" -- "$line"
}

__exarare_precmd() {
  if [ "$__exarare_state" = 0 ]; then
    "$EXARARE_BIN" __hook post --exit "$__exarare_exit"
  fi
  __exarare_state=1
}

trap '__exarare_preexec' DEBUG
PROMPT_COMMAND='__exarare_exit=$?;'"${PROMPT_COMMAND:+$PROMPT_COMMAND;}"'__exarare_precmd'
PS1="[rec] $PS1"
"#;

const ZSH_ENV: &str = r#"# Generated by exarare. Do not edit.
__exarare_zdotdir=$ZDOTDIR
ZDOTDIR=${EXARARE_ORIG_ZDOTDIR:-$HOME}
[[ -f $ZDOTDIR/.zshenv ]] && source $ZDOTDIR/.zshenv
ZDOTDIR=$__exarare_zdotdir
"#;

const ZSH_RC: &str = r#"# Generated by exarare. Do not edit.
ZDOTDIR=${EXARARE_ORIG_ZDOTDIR:-$HOME}
[[ -f $ZDOTDIR/.zshrc ]] && source $ZDOTDIR/.zshrc

__exarare_running=0

__exarare_preexec() {
  __exarare_running=1
  "$EXARARE_BIN" __hook pre --cwd "$PWD" -- "$1"
}

__exarare_precmd() {
  local exit_code=$?
  if (( __exarare_running )); then
    "$EXARARE_BIN" __hook post --exit $exit_code
  fi
  __exarare_running=0
}

preexec_functions=(__exarare_preexec $preexec_functions)
# First, so that $? is still the command's exit status.
precmd_functions=(__exarare_precmd $precmd_functions)
PROMPT="%F{red}[rec]%f $PROMPT"
"#;

/// Runs an interactive shell until it exits.
pub fn run(
    kind: Kind,
    shell: &Path,
    session_dir: &Path,
    on_spawn: impl FnOnce(u32),
) -> Result<ExitStatus> {
    let rc_dir = session_dir.join("rc");
    fs::DirBuilder::new()
        .recursive(true)
        .mode(0o700)
        .create(&rc_dir)?;

    let bin = std::env::current_exe().context("cannot locate the exarare binary")?;
    let mut cmd = Command::new(shell);
    cmd.env(ENV_SESSION_DIR, session_dir).env(ENV_BIN, &bin);

    match kind {
        Kind::Bash => {
            let rc = rc_dir.join("bashrc");
            fs::write(&rc, BASH_RC)?;
            cmd.arg("--rcfile").arg(&rc).arg("-i");
        }
        Kind::Zsh => {
            let zdotdir = rc_dir.join("zsh");
            fs::create_dir_all(&zdotdir)?;
            fs::write(zdotdir.join(".zshenv"), ZSH_ENV)?;
            fs::write(zdotdir.join(".zshrc"), ZSH_RC)?;
            cmd.env(
                ENV_ORIG_ZDOTDIR,
                std::env::var_os("ZDOTDIR").unwrap_or_default(),
            )
            .env("ZDOTDIR", &zdotdir)
            .arg("-i");
        }
    }

    let mut child = cmd
        .spawn()
        .with_context(|| format!("failed to start {}", shell.display()))?;
    on_spawn(child.id());

    // Ctrl-C and Ctrl-\ belong to the shell, not to us. Set after spawn so the
    // shell does not inherit SIG_IGN and pass it on to the commands it runs.
    unsafe {
        signal(Signal::SIGINT, SigHandler::SigIgn)?;
        signal(Signal::SIGQUIT, SigHandler::SigIgn)?;
    }
    let status = child.wait()?;
    unsafe {
        signal(Signal::SIGINT, SigHandler::SigDfl)?;
        signal(Signal::SIGQUIT, SigHandler::SigDfl)?;
    }
    Ok(status)
}
